name: login_bloc
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 
  flutter_bloc: 
  bloc:
  formz: 
  equatable: 
  meta:
  shared_preferences:
  authentication_repository:
    path: lib/packages/authentication_repository/
  user_repository:
    path: lib/packages/user_repository/
  local_storage_todos_api:
    path: lib/packages/local_storage_todos_api/
  todos_api:
    path: lib/packages/todos_api/
  todos_repository:
    path: lib/packages/todos_repository/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  bloc_test: 
  mocktail: 
  mockingjay:
  very_good_analysis:

flutter:  
  uses-material-design: true
  generate: true