name: login_bloc
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  flutter_bloc: 
  formz: 
  equatable: 
  bloc:
  meta:
  authentication_repository:
    path: lib/packages/authentication_repository/
  user_repository:
    path: lib/packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  bloc_test: 
  mocktail: 

flutter:  
  uses-material-design: true